version: '3.1'

services:
  bot:
    image: bot
    build:
      context: .
    entrypoint: ["lein", "dev"]
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - ./db:/usr/src/app/db
    # environment:
    #   BOT_TOKEN: $BOT_TOKEN
    env_file:
      - .env
    ports:
      - 54321:54321
